name: ${name}
authors: [F64_Rx, DaveDuart]
version: v${version}
description: ${description}
main: me.f64.playtime.PlayTime
api-version: ${apiVersion}

depend: [PlaceholderAPI]
commands:
  playtime:
    usage: /<command>
    aliases: [timeplayed, pt]
    description: PlayTime command for PlaytimeCommands!
