name: PlayTime
authors: [F64_Rx, DaveDuart]
version: ${project.version}
description: allows player to see how much they have played for.
main: me.f64.playtime.PlayTime
depend: [PlaceholderAPI]
api-version: '1.21'

commands:
  playtime:
    usage: /<command>
    aliases: [timeplayed, pt]
    description: PlayTime command for PlaytimeCommands!
