name: PlayTime
author: F64_Rx
version: ${project.version}
description: allows player to see how much they have played for.
main: me.f64.playtime.Main
depend: [PlaceholderAPI]

commands:
  playtime:
    usage: /<command>
    aliases: [timeplayed, pt]
    description: Shows the playtime of a player!
  playtimetop:
    usage: /<command>
    aliases: [timeplayedtop, ptt]
    description: Shows the playtime of top 10 players!
