name: PlayTime
author: F64_Rx
version: 2.9.5
description: allows player to see how much they have played for.
main: me.F64.PlayTime.Main
depend: [PlaceholderAPI]

commands:
  playtime:
    usage: /<command>
    aliases: [timeplayed, pt]
    description: Shows the playtime of a player!
  playtimetop:
    usage: /<command>
    aliases: [timeplayedtop, ptt]
    description: Shows the playtime of top 10 players!
  serveruptime:
    usage: /<command>
    aliases: [uptime, sp]
    description: Shows how long the server has been up for!